import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'about-us', loadComponent: () => import('./pages/about/about.component').then(m => m.AboutComponent) },
  { path: 'contact-us', loadComponent: () => import('./pages/contact-us/contact-us.component').then(m => m.ContactUsComponent) },
  { path: 'products', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'products/:productName', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'catalogue', loadComponent: () => import('./pages/catalogue/catalogue.component').then(m => m.CatalogueComponent) },
  { path: 'research', loadComponent: () => import('./pages/research/research.component').then(m => m.ResearchComponent) },
  { path: 'quality-assurance', loadComponent: () => import('./pages/quality-assurance/quality-assurance.component').then(m => m.QualityAssuranceComponent) },
  { path: 'product/emamectin-benzoate-5-sg', loadComponent: () => import('./pages/all-products/emamectin-benzoate-5-sg/emamectin-benzoate-5-sg.component').then(m => m.EmamectinBenzoate5SgComponent) },
  { path: 'product/proceed', redirectTo: 'product/emamectin-benzoate-5-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-75-sg', loadComponent: () => import('./pages/all-products/thiamethoxam-75-sg/thiamethoxam-75-sg.component').then(m => m.Thiamethoxam75SgComponent) },
  { path: 'product/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc', loadComponent: () => import('./pages/all-products/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc.component').then(m => m.Thiamethoxam12_6LambdaCyhalothrin9_5ZcComponent) },
  { path: 'product/thio-h', redirectTo: 'product/thiamethoxam-75-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-30-fs', loadComponent: () => import('./pages/all-products/thiamethoxam-30-fs/thiamethoxam-30-fs.component').then(m => m.Thiamethoxam30FsComponent) },
  { path: 'product/super-fs', redirectTo: 'all-products/thiamethoxam-30-fs', pathMatch: 'full' },
  { path: 'product/tolfenpyrad-15-ec', loadComponent: () => import('./pages/all-products/tolfenpyrad-15-ec/tolfenpyrad-15-ec.component').then(m => m.Tolfenpyrad15EcComponent) },
  { path: 'product/h-fun', redirectTo: 'product/tolfenpyrad-15-ec', pathMatch: 'full' },
  { path: 'product/glyphosate-41-sl', loadComponent: () => import('./pages/all-products/glyphosate-41-sl/glyphosate-41-sl.component').then(m => m.Glyphosate41SlComponent) },
  { path: 'product/glufosinate-ammonium-13-5-sl', loadComponent: () => import('./pages/all-products/glufosinate-ammonium-13-5-sl/glufosinate-ammonium-13-5-sl.component').then(m => m.GlufosinateAmmonium135SlComponent) },
  { path: 'product/glufo-13', redirectTo: 'product/glufosinate-ammonium-13-5-sl', pathMatch: 'full' },
  { path: 'product/quizalofop-ethyl-10-ec', loadComponent: () => import('./pages/all-products/quizalofop-ethyl-10-ec/quizalofop-ethyl-10-ec.component').then(m => m.QuizalofopEthyl10EcComponent) },
  { path: 'product/tembotrione-34-4-w-w-sc', loadComponent: () => import('./pages/all-products/tembotrione-34-4-w-w-sc/tembotrione-34-4-w-w-sc.component').then(m => m.Tembotrione344WwScComponent) },
  { path: 'product/paraquat-dichloride-24-sl', loadComponent: () => import('./pages/all-products/paraquat-dichloride-24-sl/paraquat-dichloride-24-sl.component').then(m => m.ParaquatDichloride24SlComponent) },
  { path: 'product/pendimethalin-30-ec', loadComponent: () => import('./pages/all-products/pendimethalin-30-ec/pendimethalin-30-ec.component').then(m => m.Pendimethalin30EcComponent) },
  { path: 'product/emamectin-benzoate-1-9-ec', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-9-ec/emamectin-benzoate-1-9-ec.component').then(m => m.EmamectinBenzoate19EcComponent) },
  { path: 'product/abamectin-1-9-ec', loadComponent: () => import('./pages/all-products/abamectin-1-9-ec/abamectin-1-9-ec.component').then(m => m.Abamectin19EcComponent) },
  { path: 'product/chlorpyriphos-20-ec', loadComponent: () => import('./pages/all-products/chlorpyriphos-20-ec/chlorpyriphos-20-ec.component').then(m => m.Chlorpyriphos20EcComponent) },
  { path: 'product/chlorpyriphos-50-cypermethrin-5-ec', loadComponent: () => import('./pages/all-products/chlorpyriphos-50-cypermethrin-5-ec/chlorpyriphos-50-cypermethrin-5-ec.component').then(m => m.Chlorpyriphos50Cypermethrin5EcComponent) },
  { path: 'product/combi-505', redirectTo: 'product/chlorpyriphos-50-cypermethrin-5-ec', pathMatch: 'full' },
  { path: 'product/cypermethrin-25-ec', loadComponent: () => import('./pages/all-products/cypermethrin-25-ec/cypermethrin-25-ec.component').then(m => m.Cypermethrin25EcComponent) },
  { path: 'product/h-cyper-25', redirectTo: 'product/cypermethrin-25-ec', pathMatch: 'full' },
  { path: 'product/fipronil-40-imidacloprid-40-wg', loadComponent: () => import('./pages/all-products/fipronil-40-imidacloprid-40-wg/fipronil-40-imidacloprid-40-wg.component').then(m => m.Fipronil40Imidacloprid40WgComponent) },
  { path: 'product/fi-40', redirectTo: 'product/fipronil-40-imidacloprid-40-wg', pathMatch: 'full' },
  { path: 'product/chlorantraniliprole-18-5-sc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-18-5-sc/chlorantraniliprole-18-5-sc.component').then(m => m.Chlorantraniliprole185ScComponent) },
  { path: 'product/cora-5', redirectTo: 'product/chlorantraniliprole-18-5-sc', pathMatch: 'full' },
  { path: 'product/profenofos-40-cypermethrin-4-ec', loadComponent: () => import('./pages/all-products/profenofos-40-cypermethrin-4-ec/profenofos-40-cypermethrin-4-ec.component').then(m => m.Profenofos40Cypermethrin4EcComponent) }, //mpire-404
  { path: 'product/mpire-404', loadComponent: () => import('./pages/all-products/mpire-404/mpire-404.component').then(m => m.Mpire404Component) }, //profenofos-40-cypermethrin-4-ec
  { path: 'product/deltamethrin-2-8-ec', loadComponent: () => import('./pages/all-products/deltamethrin-2-8-ec/deltamethrin-2-8-ec.component').then(m => m.Deltamethrin28EcComponent) },
  { path: 'product/dr-delta', redirectTo: 'product/deltamethrin-2-8-ec', pathMatch: 'full' },
  { path: 'product/novaluron-5-25-indoxacarb-4-5-sc-turbo', loadComponent: () => import('./pages/all-products/novaluron-5-25-indoxacarb-4-5-sc-turbo/novaluron-5-25-indoxacarb-4-5-sc-turbo.component').then(m => m.Novaluron525Indoxacarb45ScTurboComponent) },
  { path: 'products/insecticide/novaluron-5-25-indoxacarb-4-5-sc-turbo', loadComponent: () => import('./pages/all-products/novaluron-5-25-indoxacarb-4-5-sc-turbo/novaluron-5-25-indoxacarb-4-5-sc-turbo.component').then(m => m.Novaluron525Indoxacarb45ScTurboComponent) },
  { path: 'product/turbo', redirectTo: 'product/novaluron-5-25-indoxacarb-4-5-sc-turbo', pathMatch: 'full' },
  { path: 'products/insecticide/profenofos-50-ec', loadComponent: () => import('./pages/all-products/profenofos-50-ec/profenofos-50-ec.component').then(m => m.ProfenofosFiftyEcComponent) },
  { path: 'product/profenofos-50-ec', loadComponent: () => import('./pages/all-products/profenofos-50-ec/profenofos-50-ec.component').then(m => m.ProfenofosFiftyEcComponent) },
  { path: 'product/extra-profex', redirectTo: 'products/insecticide/profenofos-50-ec', pathMatch: 'full' },
  { path: 'products/insecticide/dimethoate-30-ec-h-gor', loadComponent: () => import('./pages/all-products/dimethoate-30-ec-h-gor/dimethoate-30-ec-h-gor.component').then(m => m.Dimethoate30EcHGorComponent) },
  { path: 'product/dimethoate-30-ec', loadComponent: () => import('./pages/all-products/dimethoate-30-ec-h-gor/dimethoate-30-ec-h-gor.component').then(m => m.Dimethoate30EcHGorComponent) },
  { path: 'product/h-gor', redirectTo: 'products/insecticide/dimethoate-30-ec-h-gor', pathMatch: 'full' },
  { path: 'products/insecticide/ethion-40-cypermethrin-5-ec-eclipse', loadComponent: () => import('./pages/all-products/ethion-40-cypermethrin-5-ec-eclipse/ethion-40-cypermethrin-5-ec-eclipse.component').then(m => m.Ethion40Cypermethrin5EcEclipseComponent) },
  { path: 'product/ethion-40-cypermethrin-5-ec', loadComponent: () => import('./pages/all-products/ethion-40-cypermethrin-5-ec-eclipse/ethion-40-cypermethrin-5-ec-eclipse.component').then(m => m.Ethion40Cypermethrin5EcEclipseComponent) },
  { path: 'product/eclipse', redirectTo: 'products/insecticide/ethion-40-cypermethrin-5-ec-eclipse', pathMatch: 'full' },
  { path: 'products/insecticide/fipronil-2-92-ec', loadComponent: () => import('./pages/all-products/fipronil-2-92-ec-chilli-h/fipronil-2-92-ec-chilli-h.component').then(m => m.Fipronil292EcChilliHComponent) },
  { path: 'product/fipronil-2-92-ec', loadComponent: () => import('./pages/all-products/fipronil-2-92-ec-chilli-h/fipronil-2-92-ec-chilli-h.component').then(m => m.Fipronil292EcChilliHComponent) },
  { path: 'product/chilli-h', redirectTo: 'products/insecticide/fipronil-2-92-ec', pathMatch: 'full' },
  { path: 'products/insecticide/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g.component').then(m => m.EmamectinBenzoate15Fipronil35ScPro5gComponent) },
  { path: 'product/emamectin-benzoate-1-5-fipronil-3-5-sc', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g.component').then(m => m.EmamectinBenzoate15Fipronil35ScPro5gComponent) },
  { path: 'product/pro-5g', redirectTo: 'products/insecticide/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g', pathMatch: 'full' },
  { path: 'products/insecticide/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo.component').then(m => m.Chlorantraniliprole93LambdaCyhalothrin46ZcAmpigoComponent) },
  { path: 'product/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo.component').then(m => m.Chlorantraniliprole93LambdaCyhalothrin46ZcAmpigoComponent) },
  // { path: 'product/ampigo', redirectTo: 'products/insecticide/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', pathMatch: 'full' },
  // { path: 'products/insecticide/imidacloprid-70-wg-extra-mida-70', loadComponent: () => import('./pages/all-products/imidacloprid-70-wg-extra-mida-70/imidacloprid-70-wg-extra-mida-70.component').then(m => m.Imidacloprid70WgExtraMida70Component) },
  { path: 'product/imidacloprid-70-wg', loadComponent: () => import('./pages/all-products/imidacloprid-70-wg-extra-mida-70/imidacloprid-70-wg-extra-mida-70.component').then(m => m.Imidacloprid70WgExtraMida70Component) },
  // { path: 'product/extra-mida-70', redirectTo: 'products/insecticide/imidacloprid-70-wg-extra-mida-70', pathMatch: 'full' },
  { path: 'products/insecticide/flufenzine-20-ec-yoddha', loadComponent: () => import('./pages/all-products/flufenzine-20-ec-yoddha/flufenzine-20-ec-yoddha.component').then(m => m.Flufenzine20EcYoddhaComponent) },
  { path: 'product/flufenzine-20-ec', loadComponent: () => import('./pages/all-products/flufenzine-20-ec-yoddha/flufenzine-20-ec-yoddha.component').then(m => m.Flufenzine20EcYoddhaComponent) },
  { path: 'product/yoddha', redirectTo: 'products/insecticide/flufenzine-20-ec-yoddha', pathMatch: 'full' },
  { path: 'product/dr-supreme', redirectTo: 'product/abamectin-1-9-ec', pathMatch: 'full' },
  { path: 'product/round', redirectTo: 'product/glyphosate-41-sl', pathMatch: 'full' },
];
