import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'about-us', loadComponent: () => import('./pages/about/about.component').then(m => m.AboutComponent) },
  { path: 'contact-us', loadComponent: () => import('./pages/contact-us/contact-us.component').then(m => m.ContactUsComponent) },
  { path: 'products', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'products/insecticide/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot', loadComponent: () => import('./pages/all-products/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot.component').then(m => m.Pyriproxyfen8Dinotefuran5Diafenthiuron18ScPilotComponent) },
  { path: 'products/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot', loadComponent: () => import('./pages/all-products/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot.component').then(m => m.Pyriproxyfen8Dinotefuran5Diafenthiuron18ScPilotComponent) },
  { path: 'product/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc', loadComponent: () => import('./pages/all-products/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot.component').then(m => m.Pyriproxyfen8Dinotefuran5Diafenthiuron18ScPilotComponent) },
  { path: 'product/pilot', redirectTo: 'products/pyriproxyfen-8-dinotefuran-5-diafenthiuron-18-sc-pilot', pathMatch: 'full' },
  { path: 'products/insecticide/deltamethrin-11-w-w-ec-delta-plus', loadComponent: () => import('./pages/all-products/deltamethrin-11-w-w-ec-delta-plus/deltamethrin-11-w-w-ec-delta-plus.component').then(m => m.Deltamethrin11WwEcDeltaPlusComponent) },
  { path: 'product/deltamethrin-11-w-w-ec', loadComponent: () => import('./pages/all-products/deltamethrin-11-w-w-ec-delta-plus/deltamethrin-11-w-w-ec-delta-plus.component').then(m => m.Deltamethrin11WwEcDeltaPlusComponent) },
  { path: 'product/delta-plus', redirectTo: 'products/insecticide/deltamethrin-11-w-w-ec-delta-plus', pathMatch: 'full' },
  { path: 'products/insecticide/fenvalerate-20-ec-fenval', loadComponent: () => import('./pages/all-products/fenvalerate-20-ec-fenval/fenvalerate-20-ec-fenval.component').then(m => m.Fenvalerate20EcFenvalComponent) },
  { path: 'products/insecticide/tolfenpyrad-15-bifenthrin-7-5-se', loadComponent: () => import('./pages/all-products/tolfenpyrad-15-bifenthrin-7-5-se-megnum/tolfenpyrad-15-bifenthrin-7-5-se-megnum.component').then(m => m.Tolfenpyrad15Bifenthrin75SeMegnumComponent) },
  { path: 'product/pyriproxyfen-10-bifenthrin-10-w-w-ec', loadComponent: () => import('./pages/all-products/pyriproxyfen-10-bifenthrin-10-w-w-ec-final/pyriproxyfen-10-bifenthrin-10-w-w-ec-final.component').then(m => m.Pyriproxyfen10Bifenthrin10WwEcFinalComponent) },
  { path: 'product/final', redirectTo: 'product/pyriproxyfen-10-bifenthrin-10-w-w-ec', pathMatch: 'full' },
  { path: 'product/tolfenpyrad-15-bifenthrin-7-5-se', loadComponent: () => import('./pages/all-products/tolfenpyrad-15-bifenthrin-7-5-se-megnum/tolfenpyrad-15-bifenthrin-7-5-se-megnum.component').then(m => m.Tolfenpyrad15Bifenthrin75SeMegnumComponent) },
  { path: 'product/megnum', redirectTo: 'products/insecticide/tolfenpyrad-15-bifenthrin-7-5-se-megnum', pathMatch: 'full' },
  { path: 'product/fenvalerate-20-ec', loadComponent: () => import('./pages/all-products/fenvalerate-20-ec-fenval/fenvalerate-20-ec-fenval.component').then(m => m.Fenvalerate20EcFenvalComponent) },
  { path: 'product/fenval', redirectTo: 'products/insecticide/fenvalerate-20-ec', pathMatch: 'full' },
  { path: 'product/chlorfenapyr-10-sc', loadComponent: () => import('./pages/all-products/chlorfenapyr-10-sc-interprid/chlorfenapyr-10-sc-interprid.component').then(m => m.Chlorfenapyr10ScInterpridComponent) },
  { path: 'products/insecticide/chlorfenapyr-10-sc', loadComponent: () => import('./pages/all-products/chlorfenapyr-10-sc-interprid/chlorfenapyr-10-sc-interprid.component').then(m => m.Chlorfenapyr10ScInterpridComponent) },
  { path: 'product/interprid', redirectTo: 'products/chlorfenapyr-10-sc-interprid', pathMatch: 'full' },
  { path: 'products/insecticide/acephate-50-imidacloprid-1-8-sp-lanser-gold', loadComponent: () => import('./pages/all-products/acephate-50-imidacloprid-1-8-sp-lanser-gold/acephate-50-imidacloprid-1-8-sp-lanser-gold.component').then(m => m.Acephate50Imidacloprid18SpLanserGoldComponent) },
  { path: 'products/insecticide/buprofezin-15-acephate-50', loadComponent: () => import('./pages/all-products/buprofezin-15-acephate-50-topaz/buprofezin-15-acephate-50-topaz.component').then(m => m.Buprofezin15Acephate50TopazComponent) },
  { path: 'product/buprofezin-15-acephate-50', loadComponent: () => import('./pages/all-products/buprofezin-15-acephate-50-topaz/buprofezin-15-acephate-50-topaz.component').then(m => m.Buprofezin15Acephate50TopazComponent) },
  { path: 'product/topaz', redirectTo: 'products/insecticide/buprofezin-15-acephate-50', pathMatch: 'full' },
  { path: 'product/acephate-50-imidacloprid-1-8-sp', loadComponent: () => import('./pages/all-products/acephate-50-imidacloprid-1-8-sp-lanser-gold/acephate-50-imidacloprid-1-8-sp-lanser-gold.component').then(m => m.Acephate50Imidacloprid18SpLanserGoldComponent) },
  { path: 'product/lanser-gold', redirectTo: 'products/insecticide/acephate-50-imidacloprid-1-8-sp-lanser-gold', pathMatch: 'full' },
  { path: 'product/acetamiprid-20-sp', loadComponent: () => import('./pages/all-products/acetamiprid-20-sp-pride-h/acetamiprid-20-sp-pride-h.component').then(m => m.Acetamiprid20SpPrideHComponent) },
  { path: 'products/insecticide/acetamiprid-20-sp', loadComponent: () => import('./pages/all-products/acetamiprid-20-sp-pride-h/acetamiprid-20-sp-pride-h.component').then(m => m.Acetamiprid20SpPrideHComponent) },
  { path: 'product/pride-h', redirectTo: 'product/acetamiprid-20-sp', pathMatch: 'full' },
  { path: 'product/acephate-75-sp', loadComponent: () => import('./pages/all-products/acephate-75-sp-hil-thene/acephate-75-sp-hil-thene.component').then(m => m.Acephate75SpHilTheneComponent) },
  { path: 'products/insecticide/acephate-75-sp', loadComponent: () => import('./pages/all-products/acephate-75-sp-hil-thene/acephate-75-sp-hil-thene.component').then(m => m.Acephate75SpHilTheneComponent) },
  { path: 'product/hil-thene', redirectTo: 'product/acephate-75-sp', pathMatch: 'full' },
  { path: 'products/chemistry-azoxystrobin-11-tebuconazole-18-3-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-11-tebuconazole-18-3-sc-chemistry/azoxystrobin-11-tebuconazole-18-3-sc-chemistry.component').then(m => m.Azoxystrobin11Tebuconazole183ScChemistryComponent) },
  { path: 'product/azoxystrobin-11-tebuconazole-18-3-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-11-tebuconazole-18-3-sc-chemistry/azoxystrobin-11-tebuconazole-18-3-sc-chemistry.component').then(m => m.Azoxystrobin11Tebuconazole183ScChemistryComponent) },
  { path: 'product/chemistry', redirectTo: 'product/azoxystrobin-11-tebuconazole-18-3-sc', pathMatch: 'full' },
  { path: 'products/captop-azoxystrobin-18-2-difenoconazole-11-4-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-18-2-difenoconazole-11-4-sc-captop/azoxystrobin-18-2-difenoconazole-11-4-sc-captop.component').then(m => m.Azoxystrobin182Difenoconazole114ScCaptopComponent) },
  { path: 'product/azoxystrobin-18-2-difenoconazole-11-4-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-18-2-difenoconazole-11-4-sc-captop/azoxystrobin-18-2-difenoconazole-11-4-sc-captop.component').then(m => m.Azoxystrobin182Difenoconazole114ScCaptopComponent) },
  { path: 'product/captop', redirectTo: 'products/captop-azoxystrobin-18-2-difenoconazole-11-4-sc', pathMatch: 'full' },
  { path: 'products/azoxystrobin-4-8-chlorothalonil-40-sc-king', loadComponent: () => import('./pages/all-products/azoxystrobin-4-8-chlorothalonil-40-sc-king/azoxystrobin-4-8-chlorothalonil-40-sc-king.component').then(m => m.Azoxystrobin48Chlorothalonil40ScKingComponent) },
  { path: 'product/azoxystrobin-4-8-chlorothalonil-40-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-4-8-chlorothalonil-40-sc-king/azoxystrobin-4-8-chlorothalonil-40-sc-king.component').then(m => m.Azoxystrobin48Chlorothalonil40ScKingComponent) },
  { path: 'product/king', redirectTo: 'products/azoxystrobin-4-8-chlorothalonil-40-sc-king', pathMatch: 'full' },
  { path: 'products/propiconazole-25-ec-h-tilt', loadComponent: () => import('./pages/all-products/propiconazole-25-ec-h-tilt/propiconazole-25-ec-h-tilt.component').then(m => m.Propiconazole25EcHTiltComponent) },
  { path: 'product/propiconazole-25-ec', loadComponent: () => import('./pages/all-products/propiconazole-25-ec-h-tilt/propiconazole-25-ec-h-tilt.component').then(m => m.Propiconazole25EcHTiltComponent) },
  { path: 'product/h-tilt', redirectTo: 'products/propiconazole-25-ec-h-tilt', pathMatch: 'full' },
  { path: 'products/validamycin-3-l-magic', loadComponent: () => import('./pages/all-products/validamycin-3-l-magic/validamycin-3-l-magic.component').then(m => m.Validamycin3LMagicComponent) },
  { path: 'product/validamycin-3-l', loadComponent: () => import('./pages/all-products/validamycin-3-l-magic/validamycin-3-l-magic.component').then(m => m.Validamycin3LMagicComponent) },
  { path: 'product/magic', redirectTo: 'products/validamycin-3-l-magic', pathMatch: 'full' },
  { path: 'products/metalaxyl-8-mancozeb-64-wp-milet-gold', loadComponent: () => import('./pages/all-products/metalaxyl-8-mancozeb-64-wp-milet-gold/metalaxyl-8-mancozeb-64-wp-milet-gold.component').then(m => m.Metalaxyl8Mancozeb64WpMiletGoldComponent) },
  { path: 'product/metalaxyl-8-mancozeb-64-wp', loadComponent: () => import('./pages/all-products/metalaxyl-8-mancozeb-64-wp-milet-gold/metalaxyl-8-mancozeb-64-wp-milet-gold.component').then(m => m.Metalaxyl8Mancozeb64WpMiletGoldComponent) },
  { path: 'product/milet-gold', redirectTo: 'products/metalaxyl-8-mancozeb-64-wp-milet-gold', pathMatch: 'full' },
  { path: 'products/mancozeb-75-wp-hari-45', loadComponent: () => import('./pages/all-products/mancozeb-75-wp-hari-45/mancozeb-75-wp-hari-45.component').then(m => m.Mancozeb75WpHari45Component) },
  { path: 'product/mancozeb-75-wp', loadComponent: () => import('./pages/all-products/mancozeb-75-wp-hari-45/mancozeb-75-wp-hari-45.component').then(m => m.Mancozeb75WpHari45Component) },
  { path: 'product/hari-45', redirectTo: 'products/mancozeb-75-wp-hari-45', pathMatch: 'full' },
  { path: 'products/thiophanate-methyl-70-wp-htm', loadComponent: () => import('./pages/all-products/thiophanate-methyl-70-wp-htm/thiophanate-methyl-70-wp-htm.component').then(m => m.ThiophanateMethyl70WpHtmComponent) },
  { path: 'product/thiophanate-methyl-70-wp', loadComponent: () => import('./pages/all-products/thiophanate-methyl-70-wp-htm/thiophanate-methyl-70-wp-htm.component').then(m => m.ThiophanateMethyl70WpHtmComponent) },
  { path: 'product/htm', redirectTo: 'products/thiophanate-methyl-70-wp-htm', pathMatch: 'full' },
  { path: 'products/carbendazim-12-mancozeb-63-wp-saf-63', loadComponent: () => import('./pages/all-products/carbendazim-12-mancozeb-63-wp-saf-63/carbendazim-12-mancozeb-63-wp-saf-63.component').then(m => m.Carbendazim12Mancozeb63WpSaf63Component) },
  { path: 'product/carbendazim-12-mancozeb-63-wp', loadComponent: () => import('./pages/all-products/carbendazim-12-mancozeb-63-wp-saf-63/carbendazim-12-mancozeb-63-wp-saf-63.component').then(m => m.Carbendazim12Mancozeb63WpSaf63Component) },
  { path: 'product/saf-63', redirectTo: 'products/carbendazim-12-mancozeb-63-wp-saf-63', pathMatch: 'full' },
  { path: 'products/picoxystrobin-propiconazole-sc-galion-way', loadComponent: () => import('./pages/all-products/picoxystrobin-7-05-propiconazole-11-71-sc-galion-way/picoxystrobin-7-05-propiconazole-11-71-sc-galion-way.component').then(m => m.PicoxystrobinPropiconazoleScGalionWayComponent) },
  { path: 'product/picoxystrobin-7-05-propiconazole-11-71-sc', loadComponent: () => import('./pages/all-products/picoxystrobin-7-05-propiconazole-11-71-sc-galion-way/picoxystrobin-7-05-propiconazole-11-71-sc-galion-way.component').then(m => m.PicoxystrobinPropiconazoleScGalionWayComponent) },
  { path: 'product/galion-way', redirectTo: 'products/picoxystrobin-propiconazole-sc-galion-way', pathMatch: 'full' },
  { path: 'products/chlorothalonil-75-wp-hatayu', loadComponent: () => import('./pages/all-products/chlorothalonil-75-wp-hatayu/chlorothalonil-75-wp-hatayu.component').then(m => m.Chlorothalonil75WpHatayuComponent) },
  { path: 'product/chlorothalonil-75-wp', loadComponent: () => import('./pages/all-products/chlorothalonil-75-wp-hatayu/chlorothalonil-75-wp-hatayu.component').then(m => m.Chlorothalonil75WpHatayuComponent) },
  { path: 'product/hatayu', redirectTo: 'products/chlorothalonil-75-wp-hatayu', pathMatch: 'full' },
  { path: 'products/lime-sulphur-22-sc-taigar-22', loadComponent: () => import('./pages/all-products/lime-sulphur-22-sc-taigar-22/lime-sulphur-22-sc-taigar-22.component').then(m => m.LimeSulphur22ScTaigar22Component) },
  { path: 'product/lime-sulphur-22-sc', loadComponent: () => import('./pages/all-products/lime-sulphur-22-sc-taigar-22/lime-sulphur-22-sc-taigar-22.component').then(m => m.LimeSulphur22ScTaigar22Component) },
  { path: 'product/taigar-22', redirectTo: 'products/lime-sulphur-22-sc-taigar-22', pathMatch: 'full' },
  { path: 'products/sulphur-55-16-sc', loadComponent: () => import('./pages/all-products/sulphur-55-16-sc-sulf-55/sulphur-55-16-sc-sulf-55.component').then(m => m.Sulphur5516ScSulf55Component) },
  { path: 'product/sulphur-55-16-sc', loadComponent: () => import('./pages/all-products/sulphur-55-16-sc-sulf-55/sulphur-55-16-sc-sulf-55.component').then(m => m.Sulphur5516ScSulf55Component) },
  { path: 'product/sulf-55', redirectTo: 'products/sulphur-55-16-sc', pathMatch: 'full' },
  { path: 'products/tricyclazole-75-wp-trizole', loadComponent: () => import('./pages/all-products/tricyclazole-75-wp-trizole/tricyclazole-75-wp-trizole.component').then(m => m.Tricyclazole75WpTrizoleComponent) },
  { path: 'product/tricyclazole-75-wp', loadComponent: () => import('./pages/all-products/tricyclazole-75-wp-trizole/tricyclazole-75-wp-trizole.component').then(m => m.Tricyclazole75WpTrizoleComponent) },
  { path: 'product/trizole', redirectTo: 'products/tricyclazole-75-wp-trizole', pathMatch: 'full' },
  { path: 'products/copper-oxychloride-50-wp-super-coc', loadComponent: () => import('./pages/all-products/copper-oxychloride-50-wp-super-coc/copper-oxychloride-50-wp-super-coc.component').then(m => m.CopperOxychloride50WpSuperCocComponent) },
  { path: 'product/copper-oxychloride-50-wp', loadComponent: () => import('./pages/all-products/copper-oxychloride-50-wp-super-coc/copper-oxychloride-50-wp-super-coc.component').then(m => m.CopperOxychloride50WpSuperCocComponent) },
  { path: 'product/super-coc', redirectTo: 'products/copper-oxychloride-50-wp-super-coc', pathMatch: 'full' },
  { path: 'products/propineb-70-wp-n-tracol', loadComponent: () => import('./pages/all-products/propineb-70-wp-n-tracol/propineb-70-wp-n-tracol.component').then(m => m.Propineb70WpNTracolComponent) },
  { path: 'product/propineb-70-wp', loadComponent: () => import('./pages/all-products/propineb-70-wp-n-tracol/propineb-70-wp-n-tracol.component').then(m => m.Propineb70WpNTracolComponent) },
  { path: 'product/n-tracol', redirectTo: 'products/propineb-70-wp-n-tracol', pathMatch: 'full' },
  { path: 'products/metalaxyl-35-ws-meta-35', loadComponent: () => import('./pages/all-products/metalaxyl-35-ws-meta-35/metalaxyl-35-ws-meta-35.component').then(m => m.Metalaxyl35WsMeta35Component) },
  { path: 'product/metalaxyl-35-ws', loadComponent: () => import('./pages/all-products/metalaxyl-35-ws-meta-35/metalaxyl-35-ws-meta-35.component').then(m => m.Metalaxyl35WsMeta35Component) },
  { path: 'product/meta-35', redirectTo: 'products/metalaxyl-35-ws-meta-35', pathMatch: 'full' },
  { path: 'products/picoxystrobin-22-52-sc-galion', loadComponent: () => import('./pages/all-products/picoxystrobin-22-52-sc-galion/picoxystrobin-22-52-sc-galion.component').then(m => m.Picoxystrobin2252ScGalionComponent) },
  { path: 'product/picoxystrobin-22-52-sc', loadComponent: () => import('./pages/all-products/picoxystrobin-22-52-sc-galion/picoxystrobin-22-52-sc-galion.component').then(m => m.Picoxystrobin2252ScGalionComponent) },
  { path: 'product/galion', redirectTo: 'products/picoxystrobin-22-52-sc-galion', pathMatch: 'full' },
  { path: 'products/dr-root-humic-amino-fulvic-vitamin-organic-carbon', loadComponent: () => import('./pages/all-products/dr-root-humic-amino-fulvic-vitamin-organic-carbon/dr-root-humic-amino-fulvic-vitamin-organic-carbon.component').then(m => m.DrRootHumicAminoFulvicVitaminOrganicCarbonComponent) },
  { path: 'product/humic-amino-fulvic-vitamin-c-e-organic-carbon', loadComponent: () => import('./pages/all-products/dr-root-humic-amino-fulvic-vitamin-organic-carbon/dr-root-humic-amino-fulvic-vitamin-organic-carbon.component').then(m => m.DrRootHumicAminoFulvicVitaminOrganicCarbonComponent) },
  { path: 'product/dr-root', loadComponent: () => import('./pages/all-products/dr-root-humic-amino-fulvic-vitamin-organic-carbon/dr-root-humic-amino-fulvic-vitamin-organic-carbon.component').then(m => m.DrRootHumicAminoFulvicVitaminOrganicCarbonComponent) },
  { path: 'products/potassium-humate-98-organic-carbon-2-nutri-power-gold', loadComponent: () => import('./pages/all-products/potassium-humate-98-organic-carbon-2-nutri-power-gold/potassium-humate-98-organic-carbon-2-nutri-power-gold.component').then(m => m.PotassiumHumate98OrganicCarbon2NutriPowerGoldComponent) },
  { path: 'product/potassium-humate-98-organic-carbon-2', loadComponent: () => import('./pages/all-products/potassium-humate-98-organic-carbon-2-nutri-power-gold/potassium-humate-98-organic-carbon-2-nutri-power-gold.component').then(m => m.PotassiumHumate98OrganicCarbon2NutriPowerGoldComponent) },
  { path: 'product/nutri-power-gold', loadComponent: () => import('./pages/all-products/potassium-humate-98-organic-carbon-2-nutri-power-gold/potassium-humate-98-organic-carbon-2-nutri-power-gold.component').then(m => m.PotassiumHumate98OrganicCarbon2NutriPowerGoldComponent) },
  { path: 'products/humic-98-plant-growth-regulator', loadComponent: () => import('./pages/all-products/humic-98-plant-growth-regulator/humic-98-plant-growth-regulator.component').then(m => m.Humic98PlantGrowthRegulatorComponent) },
  { path: 'product/humic-acid-98', loadComponent: () => import('./pages/all-products/humic-98-plant-growth-regulator/humic-98-plant-growth-regulator.component').then(m => m.Humic98PlantGrowthRegulatorComponent) },
  { path: 'product/humic-98', loadComponent: () => import('./pages/all-products/humic-98-plant-growth-regulator/humic-98-plant-growth-regulator.component').then(m => m.Humic98PlantGrowthRegulatorComponent) },
  { path: 'products/gibberellic-acid-0-001-l-husi', loadComponent: () => import('./pages/all-products/gibberellic-acid-0-001-l-husi/gibberellic-acid-0-001-l-husi.component').then(m => m.GibberellicAcid0001LHusiComponent) },
  { path: 'product/gibberellic-acid-0-001-l', loadComponent: () => import('./pages/all-products/gibberellic-acid-0-001-l-husi/gibberellic-acid-0-001-l-husi.component').then(m => m.GibberellicAcid0001LHusiComponent) },
  { path: 'product/husi', redirectTo: 'products/gibberellic-acid-0-001-l-husi', pathMatch: 'full' },
  { path: 'products/:productName', loadComponent: () => import('./pages/products/products.component').then(m => m.ProductsComponent) },
  { path: 'catalogue', loadComponent: () => import('./pages/catalogue/catalogue.component').then(m => m.CatalogueComponent) },
  { path: 'research', loadComponent: () => import('./pages/research/research.component').then(m => m.ResearchComponent) },
  { path: 'quality-assurance', loadComponent: () => import('./pages/quality-assurance/quality-assurance.component').then(m => m.QualityAssuranceComponent) },
  { path: 'product/emamectin-benzoate-5-sg', loadComponent: () => import('./pages/all-products/emamectin-benzoate-5-sg/emamectin-benzoate-5-sg.component').then(m => m.EmamectinBenzoate5SgComponent) },
  { path: 'product/proceed', redirectTo: 'product/emamectin-benzoate-5-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-75-sg', loadComponent: () => import('./pages/all-products/thiamethoxam-75-sg/thiamethoxam-75-sg.component').then(m => m.Thiamethoxam75SgComponent) },
  { path: 'product/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc', loadComponent: () => import('./pages/all-products/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc/thiamethoxam-12-6-lambda-cyhalothrin-9-5-zc.component').then(m => m.Thiamethoxam12_6LambdaCyhalothrin9_5ZcComponent) },
  { path: 'product/thio-h', redirectTo: 'product/thiamethoxam-75-sg', pathMatch: 'full' },
  { path: 'product/thiamethoxam-30-fs', loadComponent: () => import('./pages/all-products/thiamethoxam-30-fs/thiamethoxam-30-fs.component').then(m => m.Thiamethoxam30FsComponent) },
  { path: 'product/super-fs', redirectTo: 'all-products/thiamethoxam-30-fs', pathMatch: 'full' },
  { path: 'product/tolfenpyrad-15-ec', loadComponent: () => import('./pages/all-products/tolfenpyrad-15-ec/tolfenpyrad-15-ec.component').then(m => m.Tolfenpyrad15EcComponent) },
  { path: 'product/h-fun', redirectTo: 'product/tolfenpyrad-15-ec', pathMatch: 'full' },
  { path: 'product/glyphosate-41-sl', loadComponent: () => import('./pages/all-products/glyphosate-41-sl/glyphosate-41-sl.component').then(m => m.Glyphosate41SlComponent) },
  { path: 'product/glufosinate-ammonium-13-5-sl', loadComponent: () => import('./pages/all-products/glufosinate-ammonium-13-5-sl/glufosinate-ammonium-13-5-sl.component').then(m => m.GlufosinateAmmonium135SlComponent) },
  { path: 'product/glufo-13', redirectTo: 'product/glufosinate-ammonium-13-5-sl', pathMatch: 'full' },
  { path: 'product/quizalofop-ethyl-10-ec', loadComponent: () => import('./pages/all-products/quizalofop-ethyl-10-ec/quizalofop-ethyl-10-ec.component').then(m => m.QuizalofopEthyl10EcComponent) },
  { path: 'product/tembotrione-34-4-w-w-sc', loadComponent: () => import('./pages/all-products/tembotrione-34-4-w-w-sc/tembotrione-34-4-w-w-sc.component').then(m => m.Tembotrione344WwScComponent) },
  { path: 'product/paraquat-dichloride-24-sl', loadComponent: () => import('./pages/all-products/paraquat-dichloride-24-sl/paraquat-dichloride-24-sl.component').then(m => m.ParaquatDichloride24SlComponent) },
  { path: 'product/pendimethalin-30-ec', loadComponent: () => import('./pages/all-products/pendimethalin-30-ec/pendimethalin-30-ec.component').then(m => m.Pendimethalin30EcComponent) },
  { path: 'product/emamectin-benzoate-1-9-ec', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-9-ec/emamectin-benzoate-1-9-ec.component').then(m => m.EmamectinBenzoate19EcComponent) },
  { path: 'product/abamectin-1-9-ec', loadComponent: () => import('./pages/all-products/abamectin-1-9-ec/abamectin-1-9-ec.component').then(m => m.Abamectin19EcComponent) },
  { path: 'product/chlorpyriphos-20-ec', loadComponent: () => import('./pages/all-products/chlorpyriphos-20-ec/chlorpyriphos-20-ec.component').then(m => m.Chlorpyriphos20EcComponent) },
  { path: 'product/chlorpyriphos-50-cypermethrin-5-ec', loadComponent: () => import('./pages/all-products/chlorpyriphos-50-cypermethrin-5-ec/chlorpyriphos-50-cypermethrin-5-ec.component').then(m => m.Chlorpyriphos50Cypermethrin5EcComponent) },
  { path: 'product/combi-505', redirectTo: 'product/chlorpyriphos-50-cypermethrin-5-ec', pathMatch: 'full' },
  { path: 'product/cypermethrin-25-ec', loadComponent: () => import('./pages/all-products/cypermethrin-25-ec/cypermethrin-25-ec.component').then(m => m.Cypermethrin25EcComponent) },
  { path: 'product/h-cyper-25', redirectTo: 'product/cypermethrin-25-ec', pathMatch: 'full' },
  { path: 'product/fipronil-40-imidacloprid-40-wg', loadComponent: () => import('./pages/all-products/fipronil-40-imidacloprid-40-wg/fipronil-40-imidacloprid-40-wg.component').then(m => m.Fipronil40Imidacloprid40WgComponent) },
  { path: 'product/fi-40', redirectTo: 'product/fipronil-40-imidacloprid-40-wg', pathMatch: 'full' },
  { path: 'product/chlorantraniliprole-18-5-sc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-18-5-sc/chlorantraniliprole-18-5-sc.component').then(m => m.Chlorantraniliprole185ScComponent) },
  { path: 'product/cora-5', redirectTo: 'product/chlorantraniliprole-18-5-sc', pathMatch: 'full' },
  { path: 'product/profenofos-40-cypermethrin-4-ec', loadComponent: () => import('./pages/all-products/profenofos-40-cypermethrin-4-ec/profenofos-40-cypermethrin-4-ec.component').then(m => m.Profenofos40Cypermethrin4EcComponent) }, //mpire-404
  { path: 'product/mpire-404', loadComponent: () => import('./pages/all-products/mpire-404/mpire-404.component').then(m => m.Mpire404Component) }, //profenofos-40-cypermethrin-4-ec
  { path: 'product/deltamethrin-2-8-ec', loadComponent: () => import('./pages/all-products/deltamethrin-2-8-ec/deltamethrin-2-8-ec.component').then(m => m.Deltamethrin28EcComponent) },
  { path: 'product/dr-delta', redirectTo: 'product/deltamethrin-2-8-ec', pathMatch: 'full' },
  { path: 'product/novaluron-5-25-indoxacarb-4-5-sc-turbo', loadComponent: () => import('./pages/all-products/novaluron-5-25-indoxacarb-4-5-sc-turbo/novaluron-5-25-indoxacarb-4-5-sc-turbo.component').then(m => m.Novaluron525Indoxacarb45ScTurboComponent) },
  { path: 'products/insecticide/novaluron-5-25-indoxacarb-4-5-sc-turbo', loadComponent: () => import('./pages/all-products/novaluron-5-25-indoxacarb-4-5-sc-turbo/novaluron-5-25-indoxacarb-4-5-sc-turbo.component').then(m => m.Novaluron525Indoxacarb45ScTurboComponent) },
  { path: 'product/turbo', redirectTo: 'product/novaluron-5-25-indoxacarb-4-5-sc-turbo', pathMatch: 'full' },
  { path: 'products/insecticide/profenofos-50-ec', loadComponent: () => import('./pages/all-products/profenofos-50-ec/profenofos-50-ec.component').then(m => m.ProfenofosFiftyEcComponent) },
  { path: 'product/profenofos-50-ec', loadComponent: () => import('./pages/all-products/profenofos-50-ec/profenofos-50-ec.component').then(m => m.ProfenofosFiftyEcComponent) },
  { path: 'product/extra-profex', redirectTo: 'products/insecticide/profenofos-50-ec', pathMatch: 'full' },
  { path: 'products/insecticide/dimethoate-30-ec-h-gor', loadComponent: () => import('./pages/all-products/dimethoate-30-ec-h-gor/dimethoate-30-ec-h-gor.component').then(m => m.Dimethoate30EcHGorComponent) },
  { path: 'product/dimethoate-30-ec', loadComponent: () => import('./pages/all-products/dimethoate-30-ec-h-gor/dimethoate-30-ec-h-gor.component').then(m => m.Dimethoate30EcHGorComponent) },
  { path: 'product/h-gor', redirectTo: 'products/insecticide/dimethoate-30-ec-h-gor', pathMatch: 'full' },
  { path: 'products/insecticide/ethion-40-cypermethrin-5-ec-eclipse', loadComponent: () => import('./pages/all-products/ethion-40-cypermethrin-5-ec-eclipse/ethion-40-cypermethrin-5-ec-eclipse.component').then(m => m.Ethion40Cypermethrin5EcEclipseComponent) },
  { path: 'product/ethion-40-cypermethrin-5-ec', loadComponent: () => import('./pages/all-products/ethion-40-cypermethrin-5-ec-eclipse/ethion-40-cypermethrin-5-ec-eclipse.component').then(m => m.Ethion40Cypermethrin5EcEclipseComponent) },
  { path: 'product/eclipse', redirectTo: 'products/insecticide/ethion-40-cypermethrin-5-ec-eclipse', pathMatch: 'full' },
  { path: 'products/insecticide/fipronil-2-92-ec', loadComponent: () => import('./pages/all-products/fipronil-2-92-ec-chilli-h/fipronil-2-92-ec-chilli-h.component').then(m => m.Fipronil292EcChilliHComponent) },
  { path: 'product/fipronil-2-92-ec', loadComponent: () => import('./pages/all-products/fipronil-2-92-ec-chilli-h/fipronil-2-92-ec-chilli-h.component').then(m => m.Fipronil292EcChilliHComponent) },
  { path: 'product/chilli-h', redirectTo: 'products/insecticide/fipronil-2-92-ec', pathMatch: 'full' },
  { path: 'products/insecticide/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g.component').then(m => m.EmamectinBenzoate15Fipronil35ScPro5gComponent) },
  { path: 'product/emamectin-benzoate-1-5-fipronil-3-5-sc', loadComponent: () => import('./pages/all-products/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g.component').then(m => m.EmamectinBenzoate15Fipronil35ScPro5gComponent) },
  { path: 'product/pro-5g', redirectTo: 'products/insecticide/emamectin-benzoate-1-5-fipronil-3-5-sc-pro-5g', pathMatch: 'full' },
  { path: 'products/insecticide/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo.component').then(m => m.Chlorantraniliprole93LambdaCyhalothrin46ZcAmpigoComponent) },
  { path: 'product/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', loadComponent: () => import('./pages/all-products/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc-ampigo.component').then(m => m.Chlorantraniliprole93LambdaCyhalothrin46ZcAmpigoComponent) },
  // { path: 'product/ampigo', redirectTo: 'products/insecticide/chlorantraniliprole-9-3-lambda-cyhalothrin-4-6-zc', pathMatch: 'full' },
  // { path: 'products/insecticide/imidacloprid-70-wg-extra-mida-70', loadComponent: () => import('./pages/all-products/imidacloprid-70-wg-extra-mida-70/imidacloprid-70-wg-extra-mida-70.component').then(m => m.Imidacloprid70WgExtraMida70Component) },
  { path: 'product/imidacloprid-70-wg', loadComponent: () => import('./pages/all-products/imidacloprid-70-wg-extra-mida-70/imidacloprid-70-wg-extra-mida-70.component').then(m => m.Imidacloprid70WgExtraMida70Component) },
  // { path: 'product/extra-mida-70', redirectTo: 'products/insecticide/imidacloprid-70-wg-extra-mida-70', pathMatch: 'full' },
  { path: 'products/insecticide/flufenzine-20-ec-yoddha', loadComponent: () => import('./pages/all-products/flufenzine-20-ec-yoddha/flufenzine-20-ec-yoddha.component').then(m => m.Flufenzine20EcYoddhaComponent) },
  { path: 'product/flufenzine-20-ec', loadComponent: () => import('./pages/all-products/flufenzine-20-ec-yoddha/flufenzine-20-ec-yoddha.component').then(m => m.Flufenzine20EcYoddhaComponent) },
  { path: 'product/yoddha', redirectTo: 'products/insecticide/flufenzine-20-ec-yoddha', pathMatch: 'full' },
  { path: 'products/insecticide/novaluron-10-ec-runner', loadComponent: () => import('./pages/all-products/novaluron-10-ec-runner/novaluron-10-ec-runner.component').then(m => m.Novaluron10EcRunnerComponent) },
  { path: 'product/novaluron-10-ec', loadComponent: () => import('./pages/all-products/novaluron-10-ec-runner/novaluron-10-ec-runner.component').then(m => m.Novaluron10EcRunnerComponent) },
  // { path: 'product/runner', redirectTo: 'products/insecticide/novaluron-10-ec-runner', pathMatch: 'full' },
  { path: 'products/x-pro-azoxystrobin-16-7-tricyclazole-33-3-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-16-7-tricyclazole-33-3-sc-x-pro/azoxystrobin-16-7-tricyclazole-33-3-sc-x-pro.component').then(m => m.Azoxystrobin167Tricyclazole333ScXProComponent) },
  { path: 'product/azoxystrobin-16-7-tricyclazole-33-3-sc', loadComponent: () => import('./pages/all-products/azoxystrobin-16-7-tricyclazole-33-3-sc-x-pro/azoxystrobin-16-7-tricyclazole-33-3-sc-x-pro.component').then(m => m.Azoxystrobin167Tricyclazole333ScXProComponent) },
  { path: 'product/x-pro', redirectTo: 'products/x-pro-azoxystrobin-16-7-tricyclazole-33-3-sc', pathMatch: 'full' },
  { path: 'products/tebuconazole-25-9-ec-tebuja', loadComponent: () => import('./pages/all-products/tebuconazole-25-9-ec-tebuja/tebuconazole-25-9-ec-tebuja.component').then(m => m.Tebuconazole259EcTebujaComponent) },
  { path: 'product/tebuconazole-25-9-ec', loadComponent: () => import('./pages/all-products/tebuconazole-25-9-ec-tebuja/tebuconazole-25-9-ec-tebuja.component').then(m => m.Tebuconazole259EcTebujaComponent) },
  { path: 'product/tebuja', redirectTo: 'products/tebuconazole-25-9-ec-tebuja', pathMatch: 'full' },
  { path: 'product/dr-supreme', redirectTo: 'product/abamectin-1-9-ec', pathMatch: 'full' },
  { path: 'product/round', redirectTo: 'product/glyphosate-41-sl', pathMatch: 'full' },
];
